- hosts: localhost
  tasks:
    - name: add golang apt repositories to get latest golang
      ansible.builtin.apt_repository:
          repo: ppa:longsleep/golang-backports

    - name: install apt packages
      become: true
      become_user: root
      apt:
        state: present
        name:
          - apt-transport-https
          - ca-certificates
          - containerd.io
          - curl
          - docker-ce
          - docker-ce-cli
          - gnupg
          - golang-go
          - lsb-release
          - snapd
          - tree
          - zsh

    - name: install kubectl
      become: true
      become_user: root
      snap:
        name: kubectl
        classic: yes

    - name: install kind
      become: true
      become_user: root
      get_url:
        url: https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64
        dest: /usr/local/bin/kind
        mode: 755

