## use Alt-' for prefix instead of Ctrl-b
#unbind C-b
#set -g prefix M-"'"
set -g prefix ^a

# accidentally hitting space is ruinous :D
unbind Space

# reload config
unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"

# navigate panes
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# resize panes
bind ^h resize-pane -L 5
bind ^l resize-pane -R 5
bind ^k resize-pane -U 5
bind ^j resize-pane -D 5

# setup default workspace
bind 1 split-window -h \; resize-pane -x 375 \; split-window -h \; split-window -h \; select-pane -t 1 \; resize-pane -x 125 \; select-pane -t 2 \; resize-pane -x 125 \; select-pane -t 1 \; split-window -v
bind 2 split-window -h \; resize-pane -x 125 \; split-window -v \; resize-pane -y 20 \; select-pane -t 1
bind 3 split-window -h \; resize-pane -x 225 \; split-window -h \; select-pane -t 2 \; resize-pane -x 95 \; split-window -v  \; resize-pane -y 20 \; select-pane -t 1

# reset window pane sizes
bind 0 select-pane -t 0 \; resize-pane -x 50 \; select-pane -t 3 \; resize-pane -x 125 \; select-pane -t 1 \; resize-pane -x 125 \; select-pane -t 2

